# Generated by Django 3.1.6 on 2021-08-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmessagemodel',
            name='picture',
            field=models.BinaryField(),
        ),
    ]
