# Generated by Django 3.1.6 on 2021-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20210807_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmessagemodel',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
